import { DefaultMeleeWeaponModel } from "../mongoose/schemas/items-def/melee-weapon.schema";
import mongoose, { Model } from "mongoose";
import { MeleeWeaponType } from "../interfaces/item-definitions/types/melee-weapon-type.interface";
import FirearmWeaponType from "../interfaces/item-definitions/types/firearm-weapon-type.interface";
import { DefaultFirearmWeaponModel } from "../mongoose/schemas/items-def/firearm-weapon.schema";
import AmmunitionType from "../interfaces/item-definitions/types/ammunition-type.interface";
import { AmmunitionModel } from "../mongoose/schemas/items-def/ammunition.schema";
import MagazineType from "../interfaces/item-definitions/types/magazine-type.interface";
import { MagazineModel } from "../mongoose/schemas/items-def/magazine.schema";
import { DefaultItemDefinitionModel } from "../mongoose/schemas/items-def/default-item-def.schema";
import DefaultBaseItemType from "../interfaces/item-definitions/types/default-base-item-type.interface";
import MaterialType from "../interfaces/item-definitions/types/material-type.interface";
import { MaterialModel } from "../mongoose/schemas/items-def/material.schema";
import BowType from "../interfaces/item-definitions/types/bow-type.interface";
import { DefaultBowModel } from "../mongoose/schemas/items-def/bow.schema";
import EssenceType from "../interfaces/item-definitions/types/essence-type.interface";
import { DefaultEssenceModel } from "../mongoose/schemas/items-def/essence.schema";
import AttachmentItemType from "../interfaces/item-definitions/types/attachment-item-type.interface";
import { AttachmentModel } from "../mongoose/schemas/items-def/attachment.schema";
import ArmorType from "../interfaces/item-definitions/types/armor-type.interface";
import { ArmorModel } from "../mongoose/schemas/items-def/armor.schema";
import BallisticModuleType from "../interfaces/item-definitions/types/balistic-module-type.interface";
import { BallisticModuleModel } from "../mongoose/schemas/items-def/ballistic-module.schema";
import { ShieldType } from "../interfaces/item-definitions/types/shield-type.interface";
import { ShieldModel } from "../mongoose/schemas/items-def/shield.schema";
import ExplosiveType from "../interfaces/item-definitions/types/explosive-type.interface";
import { ExplosiveModel } from "../mongoose/schemas/items-def/explosive.schema";
import RigType from "../interfaces/item-definitions/types/rig-type.interface";
import { RigModel } from "../mongoose/schemas/items-def/rig.schema";
import BackpackType from "../interfaces/item-definitions/types/backpack-type.interface";
import { BackpackModel } from "../mongoose/schemas/items-def/backpack.schema";
import ClothingType from "../interfaces/item-definitions/types/clothing-type.interface";
import { ClothingModel } from "../mongoose/schemas/items-def/clothing.schema";
import MedicalType from "../interfaces/item-definitions/types/medical-type.interface";
import { MedicalModel } from "../mongoose/schemas/items-def/medical.schema";
import { FoodModel } from "../mongoose/schemas/items-def/food.schema";
import FoodType from "../interfaces/item-definitions/types/food-type.interface";
import SurvivalType from "../interfaces/item-definitions/types/survival-type.interface";
import { SurvivalModel } from "../mongoose/schemas/items-def/survival.schema";
import ChemicalType from "../interfaces/item-definitions/types/chemical-type.interface";
import { ChemicalModel } from "../mongoose/schemas/items-def/chemical.schema";
import ElectricType from "../interfaces/item-definitions/types/electric-type.interface";
import { ElectricModel } from "../mongoose/schemas/items-def/electric.schema";
import MiscType from "../interfaces/item-definitions/types/misc-type.interface";
import { MiscModel } from "../mongoose/schemas/items-def/misc.schema";
import SkillbookType from "../interfaces/item-definitions/types/skillbook-type.interface";
import { SkillbookModel } from "../mongoose/schemas/items-def/skillbook.schema";
import AnomalyInjectorType from "../interfaces/item-definitions/types/anomaly-injector-type.interface";
import { AnomalyInjectorModel } from "../mongoose/schemas/items-def/anomaly-injector.schema";
import LiquidType from "../interfaces/item-definitions/types/liquid-type.interface";
import { LiquidModel } from "../mongoose/schemas/items-def/liquid.schema";
import e from "express";
import BaseItem from "../interfaces/items/base-item.interface";
import AggregatedAllItemsType from "../interfaces/item-definitions/types/aggregated-all-items-type.interface";
import CraftableItemType from "../interfaces/item-definitions/types/craftable-type.interface";
import { CSVParserUtils } from "../utils/csv-parser.utils";

This is a placeholder for default-item-definitions.repository.ts
