import express from "express";
import * as bodyParser from "body-parser";
import ItemDefinitionsController from "./controllers/item-definitions.controller";
import DBService from "./mongoose/dbService";
import ItemDefinitionsService from "./services/item-definitions.service";
import CustomItemDefinitionRepository from "./repositories/custom-item-definitions.repository";
import DiceController from "./controllers/dice-roller.controller";
import DiceRollService from "./services/dice-roller.service";
import ItemsController from "./controllers/items.controller";
import ItemsService from "./services/items.service";
import ItemsRepository from "./repositories/items.repository";
import APIController from "./models/api-controller";
import TypeDefinitionsController from "./controllers/type-definitions.controller";
import TypeDefinitionsService from "./services/type-definitions.service";
import TypeDefinitionsRepository from "./repositories/type-definitions.repository";
import { Mongoose } from "mongoose";
import { csvUploaderMiddleware } from "./middlewares/csv-parser.middleware";
import CSVUploaderController from "./controllers/csv-uploader.controller";

import multer from "multer";
import DefaultItemDefinitionsRepository from "./repositories/default-item-definitions.repository";
import GamesController from "./controllers/games.controller";
import GamesService from "./services/games.service";
import GamesRepository from "./repositories/games.repository";
import TraitsService from "./services/traits.service";
import TraitsRepository from "./repositories/traits.repository";
import TraitsController from "./controllers/traits.controller";
import BackgroundsController from "./controllers/backgrounds.controller";
import BackgroundsService from "./services/backgrounds.service";
import BackgroundsRepository from "./repositories/backgrounds.repository";
import AbilitiesController from "./controllers/abilities.controller";
import AbilitiesService from "./services/abilities.service";
import AbilitiesRepository from "./repositories/abilities.repository";
import ModsController from "./controllers/mods.controller";
import ModsService from "./services/mods.service";
import ModsRepository from "./repositories/mods.repository";
import ConditionsController from "./controllers/conditions.controller";
import ConditionsService from "./services/conditions.service";
import ConditionsRepository from "./repositories/conditions.repository";
import CharacterController from "./controllers/character.controller";
import CharacterService from "./services/character.service";
import CharactersRepository from "./repositories/character.repository";
import { IncomingMessage, Server, ServerResponse } from "http";
import SocketIoService from "./services/socket-io/socket-io.service";
import cors from "cors";
import SessionItemsService from "./services/socket-io/items/session-items.service";
import AdminPanelController from "./controllers/admin-panel.controller";
import ContainersController from "./controllers/containers.controller";
import ContainersService from "./services/containers.service";
import ContainersRepository from "./repositories/containers.repository";
import SessionContainersService from "./services/socket-io/containers/session-containers.service";
import SessionCharactersService from "./services/socket-io/char-details/session-characters.service";
import SessionGameDetailsService from "./services/socket-io/game-details/session-game-details.service";
import LootPoolsController from "./controllers/lootpools.controller";
import LootPoolsService from "./services/lootpools.service";
import LootPoolsRepository from "./repositories/loot-pools.repository";
import GameFeedsController from "./controllers/game-feeds.controller";
import GameFeedsService from "./services/game-feeds.service";
import GameFeedsRepository from "./repositories/game-feeds.repository";
import ExpressMongoSanitize from "express-mongo-sanitize";
import FacilityDefinitionsController from "./controllers/facility-definitions.controller";
import FacilityDefinitionsService from "./services/facility-definitions.service";
import FacilityDefinitionsRepository from "./repositories/facility-definitions.repository";
import SessionHideoutsService from "./services/socket-io/hideouts/session-hideouts.service";
import HideoutsRepository from "./repositories/hideouts.repository";
import HideoutsController from "./controllers/hideouts.controller";
import HideoutsService from "./services/hideouts.service";
import NotesContentRepository from "./repositories/notes-content.repository";
import NotesContentController from "./controllers/notes.controller";
import NotesContentService from "./services/notes-content.service";
import MonsterDefinitionsRepository from "./repositories/monster-definitions.repository";
import MonsterDefinitionsService from "./services/monster-definitions.service";
import MonsterDefinitionsController from "./controllers/monster-definitions.controller";
import NpcLootPoolsController from "./controllers/npclootpools.controller";
import NpcLootPoolsService from "./services/npclootpools.service";
import NpcLootPoolsRepository from "./repositories/npclootpools.repository";
import { StaticDataStore } from "./services/socket-io/static-data-store";
import { requireAdminPassMiddleware } from "./middlewares/admin.middleware";
import AnomalyDicePoolEffectsRepository from "./repositories/anomaly-dice-pool-effect.repository";
import VehicleDefinitionsRepository from "./repositories/vehicle-definitions.repository";
import VehicleDefinitionsController from "./controllers/vehicles-definitions.controller";
import VehicleDefinitionsService from "./services/vehicle-definitions.service";
import VehiclesRepository from "./repositories/vehicles.repository";
import SessionVehiclesService from "./services/socket-io/vehicles/session-vehicles.service";
import VehiclesController from "./controllers/vehicles.controller";
import VehiclesService from "./services/vehicles.service";
import VehicleModsRepository from "./repositories/vehicle-mods.repository";
import VehicleModsController from "./controllers/vehicle-mods.controller";
import VehicleModsService from "./services/vehicle-mods.service";
import config from "./config.json";
import passport from "passport";
import { BearerStrategy, IBearerStrategyOption } from "passport-azure-ad";
import morgan from "morgan";
import SnapshotsRepository from "./repositories/snapshots.repository";
import SnapshotsService from "./services/snapshots.service";
import { InMemoryGameStateManager } from "./services/snapshots/in-memory-game-state.manager";
import ActionLogsRepository from "./repositories/action-logs.repository";
import { ActionLogsSaveHandler } from "./services/snapshots/actions-logs-save-handler";
import { SnapshotsSaveHandler } from "./services/snapshots/snapshots-save-handler";
import { stagingMiddleware } from "./middlewares/staging.middleware";

This is a placeholder for app.ts
